# Generated by Django 4.0.1 on 2022-03-06 16:41

from django.db import migrations, models
import django.db.models.deletion
import offers.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nazwa kategorii')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular_photo', sorl.thumbnail.fields.ImageField(upload_to=offers.models.upload_to, verbose_name='Zdjęcie tytułowe')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Waga')),
                ('condition', models.CharField(choices=[('new', 'Nowy'), ('used', 'Używany'), ('damaged', 'Uszkodzony')], default='new', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', sorl.thumbnail.fields.ImageField(upload_to='', verbose_name='Zdjęcie')),
                ('has_offer', models.BooleanField(default=True, verbose_name='Powiązane z ofertą')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='offers.offer', verbose_name='Oferta')),
            ],
        ),
    ]
