# Generated by Django 4.0.1 on 2022-03-06 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktywna'),
        ),
        migrations.AddField(
            model_name='offer',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='offers.Category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kolor'),
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=tinymce.models.HTMLField(default='cos', max_length=500, verbose_name='Opis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='negotiations',
            field=models.BooleanField(default=True, verbose_name='Możliwość negocjacji'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to=settings.AUTH_USER_MODEL, verbose_name='Sprzedawca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.FloatField(default=10, verbose_name='Cena'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='producer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Producent'),
        ),
        migrations.AddField(
            model_name='offer',
            name='short_description',
            field=models.CharField(default='cos', max_length=150, verbose_name='Krótki opis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(default='title', max_length=100, verbose_name='Tytuł'),
            preserve_default=False,
        ),
    ]
