# Generated by Django 4.0.1 on 2022-03-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_active_offer_categories_offer_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='condition',
            field=models.CharField(choices=[('new', 'Nowy'), ('used', 'Używany'), ('damaged', 'Uszkodzony')], default='new', max_length=10, verbose_name='Stan'),
        ),
    ]
