# Generated by Django 4.0.1 on 2022-03-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offer_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Data'),
        ),
    ]
