# Generated by Django 4.0.1 on 2022-03-10 17:09

from django.db import migrations, models
import offers.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_offer_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='has_offer',
        ),
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.SlugField(default='slug', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=sorl.thumbnail.fields.ImageField(upload_to=offers.models.upload_to_photos, verbose_name='Zdjęcie'),
        ),
    ]
