# Generated by Django 4.0.1 on 2022-03-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_remove_photo_has_offer_offer_slug_alter_offer_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kolor'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='condition',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nowy'), (2, 'Używany'), (3, 'Uszkodzony')], default=1),
        ),
        migrations.AlterField(
            model_name='offer',
            name='producer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Producent'),
        ),
    ]
