# Generated by Django 4.0.1 on 2022-04-08 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_alter_offer_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='categories',
        ),
        migrations.AddField(
            model_name='offer',
            name='categories',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='offers.category'),
            preserve_default=False,
        ),
    ]
