# Generated by Django 4.0.1 on 2022-05-04 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0008_remove_offer_categories_offer_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Data')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_buyer', to=settings.AUTH_USER_MODEL, verbose_name='Kupujący')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_offer', to='offers.offer', verbose_name='offer')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bought_seller', to=settings.AUTH_USER_MODEL, verbose_name='Sprzedawca')),
            ],
        ),
    ]
