# Generated by Django 4.0.1 on 2022-05-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='bought_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data zakupu'),
        ),
    ]
